/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstoretaba;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/** TABA Assignment
 * student number : x19227451
 * @author callum_snow 
 */
public class OnlineBookStoreUI extends javax.swing.JFrame {
private final ArrayList <Books> book;
   
    
    
    public OnlineBookStoreUI() {
        initComponents();
        book= new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        Author = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        ebookfiletxt = new javax.swing.JTextField();
        narratortxt = new javax.swing.JTextField();
        Bookbutton = new javax.swing.JRadioButton();
        audiobutton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ebooklabel = new javax.swing.JLabel();
        narratorlabel = new javax.swing.JLabel();
        Addbutton = new javax.swing.JButton();
        Removebutton = new javax.swing.JButton();
        displaybutton = new javax.swing.JButton();
        Savebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Not Easons at all online book store");

        Bookbutton.setText("Book");
        Bookbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BookbuttonMousePressed(evt);
            }
        });
        Bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookbuttonActionPerformed(evt);
            }
        });

        audiobutton.setText("audio book");
        audiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiobuttonActionPerformed(evt);
            }
        });

        jLabel2.setText(" title of book ");

        jLabel3.setText(" author");

        jLabel4.setText("Price");

        ebooklabel.setText("Ebook format");

        narratorlabel.setText("Audio Book Narrator");

        Addbutton.setText("Add");
        Addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbuttonActionPerformed(evt);
            }
        });

        Removebutton.setText("Remove");
        Removebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovebuttonActionPerformed(evt);
            }
        });

        displaybutton.setText("Display");
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });

        Savebutton.setText("Save to file");
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(ebooklabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(narratorlabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bookbutton)
                                .addGap(79, 79, 79)
                                .addComponent(audiobutton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ebookfiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(narratortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Addbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Removebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displaybutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Savebutton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bookbutton)
                    .addComponent(audiobutton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ebooklabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ebookfiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(narratorlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(narratortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbutton)
                    .addComponent(Removebutton)
                    .addComponent(displaybutton)
                    .addComponent(Savebutton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbuttonActionPerformed
       Books b = new Books();
       b.setTitle(Title.getText());
       b.setAuthor(Author.getText());
       b.setCost(Double.parseDouble(price.getText()));
       b.setNarrator(narratortxt.getText());
       b.setFiletype(ebookfiletxt.getText());
       book.add(b);
       JOptionPane.showMessageDialog(null, "Book Information has been added Successfully");
       clearText();
       
    }//GEN-LAST:event_AddbuttonActionPerformed

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
       
        for(Books b:book){
                 JOptionPane.showMessageDialog(null, "Name of Book: "+b.getTitle()+"\n"+"Name of Author: "+b.getAuthor()+"\n"+"Price: "+b.getCost()
                         +"\n"+"Narrator for Audio Book: "+b.getNarrator()+"\n"+"eBook File Type: "+b.getFiletype());
        }
        
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed
       File B;
       FileWriter FileW;
       BufferedWriter BuffW;
       String title= Title.getText();
       String author = Author.getText();
       String cost = price.getText();
       String narrator = narratortxt.getText();
       String filetype = ebookfiletxt.getText();
       
       try{
           B= new File("BookInformation.txt");
           FileW= new FileWriter(B,true);
           BuffW = new BufferedWriter(FileW);
           
           BuffW.write(title);
           
           BuffW.write(author);
           BuffW.newLine();
           BuffW.write(cost);
           BuffW.newLine();
           BuffW.write(narrator);
           BuffW.write(filetype);
           BuffW.newLine();
           BuffW.close();
           JOptionPane.showMessageDialog(null, "Book information has been saved to file");
       }
       catch(IOException e){
            System.out.println("Error saving book information to file: "+e);
        }
    }//GEN-LAST:event_SavebuttonActionPerformed

    private void RemovebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovebuttonActionPerformed
       String bookname = JOptionPane.showInputDialog(null,"Please enter name of Book ");
       for(Books b: book){
           if(b.getTitle().equals(bookname)){
               book.remove(b);
               JOptionPane.showMessageDialog(null,"Book Information has been removed Successfully");
               break;
           } 
       }
    
    }//GEN-LAST:event_RemovebuttonActionPerformed

    private void audiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiobuttonActionPerformed

        narratorlabel.setVisible(true);
        narratortxt.setVisible(true);
    }//GEN-LAST:event_audiobuttonActionPerformed

    private void BookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookbuttonActionPerformed

        narratorlabel.setVisible(false);
        narratortxt.setVisible(false);
    }//GEN-LAST:event_BookbuttonActionPerformed

    private void BookbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookbuttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookbuttonMousePressed

    
    public void clearText(){
        Title.setText("");
        Author.setText("");
        price.setText("");
        narratortxt.setText("");
        ebookfiletxt.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineBookStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineBookStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineBookStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineBookStoreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineBookStoreUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbutton;
    private javax.swing.JTextField Author;
    private javax.swing.JRadioButton Bookbutton;
    private javax.swing.JButton Removebutton;
    private javax.swing.JButton Savebutton;
    private javax.swing.JTextField Title;
    private javax.swing.JRadioButton audiobutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton displaybutton;
    private javax.swing.JTextField ebookfiletxt;
    private javax.swing.JLabel ebooklabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel narratorlabel;
    private javax.swing.JTextField narratortxt;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
